webapp/blueprints/api.py
import math

from flask import Blueprint, abort, jsonify
from flask import Flask, session, request, url_for, redirect

api_bp = Blueprint('api', __name__,
                    template_folder='templates',
                    url_prefix='/api')
__all__ = [
    "api_bp"
]

from models  import config
from backend import BackendAPI

backendapi = BackendAPI(config)

##
## User endpoints
##
@api_bp.route('/user/register', methods=['POST'])
def user_register():
    reqdata = request.get_json()

    resp = backendapi.user_register(
        reqdata["firstname"],
        reqdata["surname"],
        reqdata["email"]
    )

    if ( resp.get("verification_code", False) ):
        session["ver_code"]       = resp["verification_code"]
        session["email"]          = reqdata["email"]
        resp["verification_code"] = "this is obviously wrong"
        return jsonify({
            "status": "ok",
            "user_uuid": resp["user_uuid"]
        })
    else:
        return jsonify({
            "status": resp["status"],
            "msg": resp.get("msg")
        })

@api_bp.route('/user/verify/email', methods=['POST'])
def user_login_by_verifying_email():
    dt = request.get_json()

    resp = backendapi.verify_with_email(dt["email"], dt["ver_code"])

    if ( resp["status"] == "ok" ):
        session["user_id"]        = resp["user"]["uuid"]
        session["user_firstname"] = resp["user"]["firstname"]
        session["user_surname"]   = resp["user"]["surname"]
        session.pop("email")
        del resp["user"]

    return jsonify({
        "status": "ok",
        **resp
    })

@api_bp.route('/user/verify/login/code', methods=['POST'])
def user_login_verify_login_code():
    dt = request.get_json()

    ver_code = dt["ver_code"]
    email = session["email"]

    resp = backendapi.user_login_with_email_verify_code(email,ver_code)

    if ( resp["status"] == "ok" ):
        session["user_id"]        = resp["user"]["uuid"]
        session["user_firstname"] = resp["user"]["firstname"]
        session["user_surname"]   = resp["user"]["surname"]
        session.pop("email")
        del resp["user"]

    return jsonify({
        "status": "ok",
        **resp
    })

@api_bp.route('/user/login/with/email', methods=['POST'])
def user_login_with_email():
    if session.get("user_id") != None: return redirect(url_for('proposals'))

    dt = request.get_json()

    resp = backendapi.user_login_with_email(dt["email"])

    if resp["status"] == "ok":
        session["email"] = resp["email"]
        session["uuid"]  = resp["user_uuid"]
        ver_code         = resp["verification_code"]

        resp = backendapi.user_login_with_email_send_login_code(
            resp["user_uuid"],
            ver_code,
        )

        return jsonify({ "status": "ok", **resp })

    elif resp["status"] == "email_not_verified":
        session["email"] = resp["email"]

    return jsonify(resp)

@api_bp.route('/user/resend/verify/email', methods=['POST'])
def user_resend_verify_code():
    return jsonify(backendapi.user_resend_verify_code(
        request.get_json()["email"]
    ))

@api_bp.route('/user/send/verify/email', methods=['POST'])
def send_verify_email():
    if session.get("ver_code") == None: return redirect(url_for('index'))

    resp = backendapi.send_email_with_verification(
        request.get_json()["user_uuid"],
        session.pop("ver_code")
    )

    return jsonify({
        "status": "ok",
        **resp
    })

@api_bp.route('/users/proposals', methods=['GET'])
def user_proposals():
    if session.get("user_id") == None: return redirect(url_for('index'))

    return jsonify(backendapi.user_proposals(
        session.get("user_id"),
        request.args.get("kind", None)
    ))

@api_bp.route('/users/getemail', methods=['GET'])
def user_getemail():
    if session.get("user_id") == None: return redirect(url_for('index'))

    return jsonify(backendapi.user_email(session.get("user_id")))


##
## Auction endpoints
##
@api_bp.route('/proposals/bid', methods=['POST'])
def proposals_bid():
    if session.get("user_id") == None: return redirect(url_for('index'))

    dt = request.get_json()

    r = backendapi.make_bid(session.get("user_id"),
                            dt["proposal_uuid"],
                            math.ceil( int(dt["amount"]) *
                                       (1 + int(dt["percent"])/100.0)))
    return jsonify({
        "status": "ok",
        **r
    })

@api_bp.route('/proposals/decline', methods=['POST'])
def proposals_decline():
    if session.get("user_id") == None: return redirect(url_for('index'))

    dt = request.get_json()

    r = backendapi.make_bid_decision(session.get("user_id"),
                                     dt["proposal_uuid"],
                                     dt["amount"],
                                     "decline")
    return jsonify({
        "status": "ok",
        **r
    })

@api_bp.route('/proposals/accept', methods=['POST'])
def proposals_accept():
    if session.get("user_id") == None: return redirect(url_for('index'))

    dt = request.get_json()

    r = backendapi.make_bid_decision(session.get("user_id"),
                                     dt["proposal_uuid"],
                                     dt["amount"],
                                     "accept")
    return jsonify({
        "status": "ok",
        **r
    })

@api_bp.route('/proposals/all', methods=['GET'])
def proposals_all():
    if session.get("user_id") == None: return redirect(url_for('index'))

    return jsonify({
        "status": "ok",
        "data": backendapi.all_proposals(False)
    })

@api_bp.route('/proposal/new', methods=["POST"])
def submit_new_proposal():
    if session.get("user_id") == None: return redirect(url_for('index'))

    dt = request.get_json()

    if not dt["amount"] or dt["amount"] == "" or int(dt["amount"]) <= 0:
        return jsonify({
            "status": "error",
            "msg": "amount NaN"
        })
    else:
        return jsonify({
            "status": "ok",
            **backendapi.new_proposal(session.get("user_id"),
                                      session.get("user_firstname"),
                                      session.get("user_surname"),
                                      dt["iamseller"],
                                      dt["description"],
                                      dt["seller_email"],
                                      int(dt["amount"]))
        })

##
## Bid endpoints
##
@api_bp.route('/bids/<bid_uuid>', methods=['GET'])
def previous_bids_for_bid(bid_uuid):
    return jsonify(backendapi.bid_details(bid_uuid))


##
## Don't spam me endpoint
##
@api_bp.route('/dont-spam-me', methods=['POST'])
def user_dont_spam_me():
    dt = request.get_json()

    return jsonify(backendapi.user_dont_spam_me(dt["data"],dt["email"]))

webapp/templates/405.html
{% extends "layout.html" %}

{% block head %}
  <title>Not Allowed</title>
  {% with libs="bootstrap" %}
    {% include "_jslibs.html" %}
  {% endwith %}
{% endblock %}

{% block body %}
Not allowed.
{% endblock %}

webapp/templates/account.html
{% extends "layout.html" %}

{% block head %}
    <title>BNBC ACCOUNT PAGE</title>
  {% with libs="bootstrap,jquery,jquery-ui,underscore" %}
    {% include "_jslibs.html" %}
  {% endwith %}
  {% include "_css.html" %}
{% endblock %}

{% block inline_css %}
{% endblock %}

{% block js_globals %}
var socket = new WebSocket('{{ getenv("WEBSOCKET_SERVER") }}/ws/bnbc');
var button_tmpl = null;
var buttons_when_accepted_tmpl = null;
var buttons_when_seller_tmpl = null;
var declinedAmountsByProposal = {};
var lsting_tmpl = null;
{% endblock %}

{% block js_functions %}
function upBidBy(elem,percent) {
  Helpers.axPost( "{{ url_for('api.proposals_bid') }}", {
    "proposal_uuid": $(elem).data("proposal-id"),
    "amount": $('#proposal-'+$(elem).data("proposal-id")).find(".bid-amount").data("amount"),
    "percent": percent
   }, (data) => {
   })
}

function declineBidAt(elem) {
  Helpers.axPost( "{{ url_for('api.proposals_decline') }}", {
    "proposal_uuid": $(elem).data("proposal-id"),
    "amount": $('#proposal-'+$(elem).data("proposal-id")).find(".bid-amount").data("amount"),
  }, (resp) => {
    if ( resp.status == "ok" ) {
      $("#buttons").fadeOut(500);
    }
  })
}

function acceptBidAt(elem) {
  Helpers.axPost( "{{ url_for('api.proposals_accept') }}", {
    "proposal_uuid": $(elem).data("proposal-id"),
    "amount": $('#proposal-'+$(elem).data("proposal-id")).find(".bid-amount").data("amount"),
  }, (resp) => {
    if ( resp.status == "ok" ) {
      $("#buttons").fadeOut(500);
    }
  })
}

function strikeThroughDeclined( newValue ) {
  if ( newValue ) { allDeclinedAmounts.push( newValue  ); };
  _.each( allDeclinedAmounts, (amt) => {
    $('.amount-' + amt ).css('text-decoration', 'line-through');
  });
}
function strikeThroughDeclinedBids( proposal_uuid, amount ) {
  if ( amount ) { declinedAmountsByProposal[proposal_uuid] = amount };
  _.each( declinedAmountsByProposal, (amount,uuid) => {
    $('#proposal-'+uuid).find(".amount-"+amount).css('text-decoration','line-through');
    $('#proposal-'+uuid).find(".seller-buttons").fadeOut(400);
  });
}

function loadProposals(kind) {
  $('#nav-'+kind).html( tmplt('loader')() );
  Helpers.axGet( "{{ url_for('api.user_proposals') }}?kind="+kind, function(resp) {
    setTimeout( () => {
      if ( resp.data.length == 0 ) {
        $('#nav-'+kind).fadeOut(200, () => {
          $('#nav-'+kind).html( tmplt('zero_count')() ).fadeIn(200);
        });
      } else {
        $('#nav-'+kind).html( lsting_tmpl() );
        _.each( resp.data, function(dr) { add_object_to_list(dr) } );
      }
    }, 500);
  });
}

function initSocket() {
  socket.onmessage = function (msg) {
    var dt = JSON.parse(msg.data);
    if ( dt.type == "new_auction" ) {
      add_object_to_list(dt.data);
    }

    if ( dt.type == "auction_creator" ) {
      dt = dt.data;
      $('#proposal-'+dt.uuid).find(".creator").html(dt.name);
    }

    if ( dt.type == "bid_accepted" ) {
      dt = dt.data;
      var html = buttons_when_accepted_tmpl({ proposal_id: dt.proposal_uuid });
      $('#proposal-'+dt.proposal_uuid).find(".bid-actions").html(html);
    }

    if ( dt.type == "bid_declined" ) {
      dt = dt.data;
      $('#proposal-'+dt.proposal_uuid).find(".amount-"+dt.amount).css('text-decoration','line-through');
      $('#proposal-'+dt.proposal_uuid).find(".seller-buttons").fadeOut(400);
    }

    if ( dt.type == "highest_bid" ) {
      dt = dt.data;

      if ( $('#proposal-'+dt.proposal_uuid).find(".bid-amount").data("amount") == dt.amount ) { return ; }

      $('#proposal-'+dt.proposal_uuid).find(".bid-amount").fadeOut(500, () => {
        $('#proposal-'+dt.proposal_uuid).find(".bid-amount").html(
          "<span class='dollars amount-"+dt.amount+"'>"+dt.amount+"</span>"
        ).data("amount",dt.amount).fadeIn(500, () => {
          if ( dt.declined ) {
            strikeThroughDeclinedBids( dt.proposal_uuid, dt.amount );
          }
        });
      });

      $('#proposal-'+dt.proposal_uuid).find(".bid-user").fadeOut(300, () => {
        $('#proposal-'+dt.proposal_uuid).find(".bid-user").html(dt.bidder_firstname + " " + dt.bidder_surname + ".").fadeIn(300);
      });

      if ( dt.bidder_uuid == "{{ session['user_id']}}" ) {
        $('#proposal-'+dt.proposal_uuid).find(".seller-buttons").fadeOut(400);
      } else {
        $('#proposal-'+dt.proposal_uuid).find(".seller-buttons").fadeIn(400);
      }
    }
  };

  socket.onopen = function() {
    if ( window.timerId ) {
      clearInterval( window.timerId );
      window.timerId = null;
    }
  };
  socket.onclose = function() {
    if ( !window.timerId ) {
      window.timerId = setInterval( function() {
        socket = new WebSocket('{{ getenv("WEBSOCKET_SERVER") }}/ws/bnbc');
        initSocket();
      }, 1000);
    }
  };
}

function add_object_to_list(data) {
  var trstr = "<tr data-id='" + data.uuid + "' id='proposal-"+data.uuid+"'>"

  trstr += "<td>" + tmplt("proposal_description")({ proposal: data }) + "</td>"

  trstr += "<td class='bid-user'><img src='/static/images/loader.svg'/></td>";

  trstr += "<td class='bid-amount'><img src='/static/images/loader.svg'/></td>";
  trstr += "<td class='bid-actions'>";
  if ( data.is_accepted ) {
    trstr += buttons_when_accepted_tmpl({ proposal_id: data.uuid });
  } else {
    if ( data.seller_uuid == "{{ session['user_id']}}" ) {
      trstr += buttons_when_seller_tmpl({ proposal_id: data.uuid });
    } else {
      trstr += button_tmpl({ proposal_id: data.uuid });
    }
  }
  trstr += "</td>";

  socket.send( JSON.stringify( {
    type: "get_creator_for_proposal",
    proposal_uuid: data.uuid
  }));

  socket.send( JSON.stringify( {
    type: "get_highest_bid",
    proposal_uuid: data.uuid
  }));

  trstr += "</tr>"
  $('#proposallisting').find('tbody').prepend(trstr)
}

{% endblock %}

{% block js_onready %}
lsting_tmpl = tmplt('proposallisting');
button_tmpl = tmplt('proposal_buttons');
buttons_when_accepted_tmpl = tmplt('proposal_buttons_when_accepted');
buttons_when_seller_tmpl = tmplt('proposal_buttons_when_seller');

initSocket();
setTimeout(() => { loadProposals('offers') }, 500);

setTimeout(() => {
  Helpers.axGet( "{{ url_for('api.user_getemail') }}", function(resp) {
    if ( resp.status == "ok" && resp.data.uuid == "{{ session.get('user_id') }}") {
      $('#email-field').fadeOut(300, () => {
        $('#email-field').html(resp.data.email).fadeIn(300)
      });
    } else {
      console.log(resp)
      $('#email-field').fadeOut(300, () => {
        $('#email-field').html("-").fadeIn(300)
      });
    }
  });

}, 123);

$('#nav-offers-tab').on('shown.bs.tab', (e) => {
  loadProposals('offers');
});
$('#nav-proposals-tab').on('shown.bs.tab', (e) => {
  loadProposals('proposals');
});
$('#nav-desires-tab').on('shown.bs.tab', (e) => {
  loadProposals('desires');
});
$('#nav-highest-bidder-tab').on('shown.bs.tab', (e) => {
  loadProposals('highest-bidder');
});
$('#nav-bidding-tab').on('shown.bs.tab', (e) => {
  loadProposals('bidding');
});

$('#nav-offers-tab').on('hide.bs.tab', (e) => { $('#nav-offers').html("");});
$('#nav-proposals-tab').on('hide.bs.tab', (e) => { $('#nav-proposals').html(""); });
$('#nav-desires-tab').on('hide.bs.tab', (e) => { $('#nav-desires').html(""); });
$('#nav-highest-bidder-tab').on('hide.bs.tab', (e) => {$('#nav-highest-bidder').html("");});
$('#nav-bidding-tab').on('hide.bs.tab', (e) => { $('#nav-bidding').html(""); });

{% endblock %}

{% block underscore_templates %}
  <div id="_tmpl_zero_count">
  <!--
  <div class='row mt-4'>
    <div class='col text-center'>
      None
    </div>
  </div>
  -->
  </div>

  <div id="_tmpl_proposallisting">
  <!--
    <div class="row">
      <div id="proposallisting" class="col">
        <table class="table table-striped">
          <thead>
            <th >Auction</th>
            <th colspan=2>Top Bidder</th>
            <th ></th>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  -->
  </div>

  <div id="_tmpl_loader">
  <!--
  <div class='row mt-4'>
    <div class='col-12'>
      <div class="container-fluid"
           style="overflow-y: hidden; overflow-x: auto;">
        <div class="row flex-row flex-nowrap" >
          <img id=loader
               width=30
               height=30
               src='/static/images/loader.svg'/>
        </div>
      </div>
    </div>
  </div>
  -->
  </div>

  <div id="_tmpl_proposal_description">
  <!--
    <a href="{{ url_for( 'proposal_view',auction_uuid='' ) }}<%= proposal.uuid %>">
       <%= proposal.text %>
    </a>
  -->
  </div>

  <div id="_tmpl_proposal_buttons_when_accepted">
  <!--
     <div class="row">
       <div class="col">
         <i class="far fa-check"></i>
       </div>
     </div>
  -->
  </div>

  <div id="_tmpl_proposal_buttons_when_seller">
  <!--
     <div class="seller-buttons row vstack gap-2">
       <div class="col">
         <a href="#"
            data-proposal-id="<%= proposal_id %>"
            class="btn btn-sm btn-success"
            type="button"
            onclick="acceptBidAt(this); return false;"
           >Accept</a>
       </div>
       <div class="col">
         <a href="#"
            data-proposal-id="<%= proposal_id %>"
            class="btn btn-danger btn-sm"
            type="button"
            onclick="declineBidAt(this); return false;"
           >Decline</a>
       </div>
     </div>
   -->
  </div>

  <div id="_tmpl_proposal_buttons">
  <!--
     <div class="row vstack hstack-sm gap-2">
       <div class="col">
         <a href="#"
            data-proposal-id="<%= proposal_id %>"
            class="btn btn-outline-danger btn-sm"
            type="button"
            onclick="upBidBy(this, 1); return false;"
           >+1%</a>
       </div>
       <div class="col">
         <a href="#"
            data-proposal-id="<%= proposal_id %>"
            class="btn btn-outline-success btn-sm"
            type="button"
            onclick="upBidBy(this, 5); return false;"
           >+5%</a>
       </div>
       <div class="col">
         <a href="#"
            data-proposal-id="<%= proposal_id %>"
            class="btn btn-outline-primary btn-sm"
            type="button"
            onclick="upBidBy(this, 10); return false;"
           >+10%</a>
       </div>
     </div>
  -->
  </div>
{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="col-12 offset-sm-2 col-sm-8" id="title-text">
      {{ read_md_file('account') | markdown }}
    </div>
  </div>

  <nav>
    <div class="nav nav-tabs col-12 offset-sm-2 col-sm-8" id="nav-tab" role="tablist">
      <button class="nav-link active"
              id="nav-offers-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-offers"
              type="button"
              role="tab"
              aria-controls="nav-offers"
              aria-selected="true"
              >Offers</button>

      <button class="nav-link"
              id="nav-proposals-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-proposals"
              type="button"
              role="tab"
              aria-controls="nav-proposals"
              aria-selected="false"
              >Proposals</button>

      <button class="nav-link"
              id="nav-desires-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-desires"
              type="button"
              role="tab"
              aria-controls="nav-desires"
              aria-selected="false"
              >Desires</button>

      <button class="nav-link"
              id="nav-highest-bidder-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-highest-bidder"
              type="button"
              role="tab"
              aria-controls="nav-highest-bidder"
              aria-selected="false"
              >Highest Bidder</button>

      <button class="nav-link"
              id="nav-bidding-tab"
              data-bs-toggle="tab"
              data-bs-target="#nav-bidding"
              type="button"
              role="tab"
              aria-controls="nav-bidding"
              aria-selected="false"
              >Bidding</button>
    </div>
  </nav>

  <div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active col-12 offset-sm-2 col-sm-8"
         id="nav-offers"
         role="tabpanel"
         aria-labelledby="nav-offers-tab"
         tabindex="0"></div>

    <div class="tab-pane fade col-12 offset-sm-2 col-sm-8"
         id="nav-proposals"
         role="tabpanel"
         aria-labelledby="nav-proposals-tab"
         tabindex="0"></div>

    <div class="tab-pane fade col-12 offset-sm-2 col-sm-8"
         id="nav-desires"
         role="tabpanel"
         aria-labelledby="nav-desires-tab"
         tabindex="0"></div>

    <div class="tab-pane fade col-12 offset-sm-2 col-sm-8"
         id="nav-highest-bidder"
         role="tabpanel"
         aria-labelledby="nav-highest-bidder-tab"
         tabindex="0"></div>

    <div class="tab-pane fade col-12 offset-sm-2 col-sm-8"
         id="nav-bidding"
         role="tabpanel"
         aria-labelledby="nav-bidding-tab"
         tabindex="0"></div>
  </div>

{% endblock %}

webapp/templates/auction_show_accepted.html
{% extends "layout.html" %}

{% block head %}
    <title>BNBC AUCTION PAGE</title>
  {% with libs="bootstrap,jquery,jquery-ui,underscore,moment" %}
    {% include "_jslibs.html" %}
  {% endwith %}
  {% include "_css.html" %}
{% endblock %}

{% block inline_css %}
{% endblock %}

{% block js_globals %}
var proposalCreatedAt = moment('{{ proposal["proposal_created_at"] | safe }}');
{% endblock %}

{% block js_functions %}

function upBidBy(elem,percent) {
  Helpers.axPost( "{{ url_for('api.proposals_bid') }}", {
    "proposal_uuid": $(elem).data("proposal-id"),
    "amount": $('#proposal-amount').data("amount"),
    "percent": percent
   }, (data) => {})
}

function obtainBids(bid_uuid) {
    Helpers.axGet( "{{ url_for('api.previous_bids_for_bid',bid_uuid='') }}" + bid_uuid, (data) => {
      if ( data.status == "ok" ) {
        if ( data.data.length == 1 && data.data[0].pb_firstname == null) {
          var tmpl = tmplt('no_previous_bids');
          $('#no_previous_bids_container').html( tmpl() );
        } else {
          $('#no_previous_bids_container').remove();
          var tmpl = tmplt('show_previous_bid');
          _.each( data.data, function(pb) {
            var newbid = $( tmpl({
              amount: pb.previous_amount,
              firstname: pb.pb_firstname,
              surname: pb.pb_surname,
              created_at: pb.pb_created_at,
              ismine: ("{{ session['user_id'] }}" == pb.pb_uuid)
            }));
            newbid.hide();
            $('#previous_bids_container').append( newbid );
            newbid.fadeIn(200);
          });
        }
      }
    });
}

{% endblock %}

{% block js_onready %}
setTimeout( function() { obtainBids( '{{ proposal["bid_uuid"] }}' ) }, 500);

var tmpl = tmplt('current_highest_bid');

$('#current_highest_bid_container').html( tmpl( {
  amount: "{{ proposal['amount'] }}",
  firstname: "{{ proposal['bidder_firstname'] }}",
  surname: "{{ proposal['bidder_surname'] }}",
  created_at: "{{ proposal['last_bid_at'] }}",
  ismine: ( "{{ proposal['bidder_uuid'] }}" == "{{ session['user_id'] }}")
}));

setTimeout( function() {
  $('#proposal-created-at').fadeOut( 400, () => {
    $('#proposal-created-at').html(proposalCreatedAt.format('LLL')).fadeIn(400);
  });
},300);

{% endblock %}

{% block underscore_templates %}
  <div id="_tmpl_no_previous_bids">
  <!--
  <div class="row mt-4">
    <div class="offset-2 col-8 text-center text-info">
      No Previous Bids
    </div>
  </div>
  -->
  </div>

  <div id="_tmpl_show_previous_bid">
  <!--
  <div class="row mt-4" >
    <div class="offset-2 col-8 offset-md-3 col-md-6 offset-lg-4 col-lg-4 text-center"
       <% if ( ismine ) { %>
       style="border: 4px solid black;"
       <% } else { %>
       style="border: 4px solid black;"
       <% } %>
       >
      <div class="row">
        <div class="col-12 text-center">
          <span class=dollars><%= amount %></span>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center">
          by <%= firstname %> <%= surname %>.
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center">
          On <%= moment(created_at).format('LLL') %>
        </div>
      </div>
    </div>
  </div>
  -->
  </div>

  <div id="_tmpl_current_highest_bid">
  <!--
  <div class="row mt-4" id="bid-amount-<%= amount %>">
  <div class="offset-2 col-8 offset-md-3 col-md-6 offset-lg-4 col-lg-4 text-center"
       <% if ( ismine ) { %>
       style="border: 4px solid black; background-color: #11994545;"
       <% } else { %>
       style="border: 4px solid black;"
       <% } %>
  >
      <div class="row"
           id="current_highest_bid"
           data-amount="<%= amount %>"
           data-firstname="<%= firstname %>"
           data-surname="<%= surname %>"
           data-created_at="<%= created_at %>"
           data-ismine="<% if (ismine) { %>true<% } else { %>false<% } %>"
           >
       <% if ( ismine ) { %>
        <div class="col-12 text-center h5">
             The seller has accepted your proposal of
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center h3">
          <span id="proposal-amount"
                class="dollars"
                data-amount="<%= amount %>"
                 ><%= amount %></span>
        </div>
      </div>

      <div class="row">
        <div class="col-12 text-center">
          On <%= moment(created_at).format('LLL') %>
        </div>
      </div>

      <div class="row">
        <div class="col-12 text-center h5">
          Congratulations!
        </div>
      </div>
       <% } else { %>
        <div class="col-12 text-center h5">
             Auction accepted for
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center h3">
          <span id="proposal-amount"
                class="dollars"
                data-amount="<%= amount %>"
                 ><%= amount %></span>
        </div>
      </div>
      <div class="row">
        <div class="col-12 text-center h5">
          bid made by <%= firstname %> <%= surname %>.
        </div>
      </div>

      <div class="row">
        <div class="col-12 text-center">
          On <%= moment(created_at).format('LLL') %>
        </div>
      </div>

      <% } %>

    </div>
  </div>
  -->
  </div>

{% endblock %}

{% block body %}
  <div class="row mt-4">
    <div class="offset-1 col-10 h2 text-center text-success">
      Auction has been accepted.
    </div>
  </div>

  <div class="row mt-4">
    <div class="offset-2 col-8 offset-md-2 col-md-8 offset-xl-3 col-xl-6 border border-dark">
      <div class="row">
        <div class="col">
          <i class="h6">Auction:</i>
        </div>
      </div>
      <div class="row">
        <div class="text-center">
          {{ proposal["text"] | safe }}
        </div>
      </div>

      <div class="row mt-2">
        <div class="col">
          <i class="h6">Seller:</i>
          {{ proposal["seller_details"] | safe }}
        </div>
      </div>

      <div class="row mt-1">
        <div class="col">
          <i class="h6">Created:</i>
          <span id="proposal-created-at">{{ proposal["proposal_created_at"] | safe }}</span>
        </div>
      </div>
    </div>
  </div>

  <div id="current_highest_bid_container">
  </div>


  <hr>
  <div class="row mt-4">
    <div class="offset-2 col-8 text-center">
      Previous Bids
    </div>
  </div>

  <div id="no_previous_bids_container" class="mt-4">
  </div>
  <div id="previous_bids_container" class="mt-4">
  </div>
{% endblock %}